import type { Metadata } from "next";
import "./globals.css";

import { Inter, Outfit } from "next/font/google";

const display = Outfit({
  subsets: ["latin", "latin-ext"],
  variable: "--font-display",
});
const sans = Inter({
  subsets: ["latin", "latin-ext"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pl'>
      <head></head>
      <body
        className={`${display.variable} ${sans.variable} bg-neutral-light antialiased`}>
        {children}
      </body>
    </html>
  );
}
